
name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
  
    runs-on: ubuntu-latest
  
    steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
        jave-version: '11'
	distibution: 'adopt'
     - name: Build with Maven
     	run: mvn -B -e verify
  
